// 项目常量定义
export const CONSTANTS = {
  PROJECT: process.env.VUE_APP_PROJECT,
  REMOTE_CONFIG_SAMPLE: process.env.VUE_APP_SUBCONVERTER_REMOTE_CONFIG,
  DOC_ADVANCED: process.env.VUE_APP_SUBCONVERTER_DOC_ADVANCED,
  BACKEND_RELEASE: process.env.VUE_APP_BACKEND_RELEASE,
  DEFAULT_BACKEND: process.env.VUE_APP_SUBCONVERTER_DEFAULT_BACKEND + '/sub?',
  SHORT_URL_API: process.env.VUE_APP_MYURLS_API,
  CONFIG_UPLOAD_API: process.env.VUE_APP_CONFIG_UPLOAD_API,
  BOT_LINK: process.env.VUE_APP_BOT_LINK,
  DEFAULT_CLIENT_TYPE: 'clash',
  BUTTON_WIDTH: '140px',
  LARGE_BUTTON_WIDTH: '290px'
};
